spring.application.name=apiLogin


jwt.secret= FlamengoCampeaoLibertadores2026MuitoMaiorQue32BytesAgora
jwt.expiration= 8600000


user.username= teste@gmail.com
user.password= teste4434


spring.datasource.url= jdbc:postgresql://dpg-d8oa9krsq97s73fcuce0-a.virginia-postgres.render.com:5432/login_nd3b
spring.datasource.username= login_nd3b_user
spring.datasource.password= qCr4BrJFLA5Qf3Zf5jKLjsL2H3f59yoa
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}
server.address=0.0.0.0
